server:
  port: 9991
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: mick
    password: mick
    driver-class-name: org.postgresql.Driver
